//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3DumpChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3DumpChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используя это программное обеспечение, вы понимаете, что автор (Swizzy) никоим образом не несет ответственности за ЛЮБОЙ ущерб, нанесенный вашей консоли...
        ///
        ///Вы также осознаёте и понимаете, что этот инструмент не является стопроцентной проверкой ваших дампов, он предназначен только для того, чтобы упростить проверку того, стоит ли к нему присматриваться или нет...
        ///
        ///Вы читали эти условия?.
        /// </summary>
        internal static string AcceptTermsMessage {
            get {
                return ResourceManager.GetString("AcceptTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используя это программное обеспечение, вы понимаете, что автор (Swizzy) никоим образом не несет ответственности за ЛЮБОЙ ущерб, нанесенный вашей консоли...
        ///
        ///Вы также осознаёте и понимаете, что этот инструмент не является стопроцентной проверкой ваших дампов, он предназначен только для того, чтобы упростить проверку того, стоит ли к нему присматриваться или нет...
        ///
        ///Вы пропустили чтение этих условий?.
        /// </summary>
        internal static string AcceptTermsMessageReversed {
            get {
                return ResourceManager.GetString("AcceptTermsMessageReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты умеешь читать?.
        /// </summary>
        internal static string AcceptTermsTitle {
            get {
                return ResourceManager.GetString("AcceptTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже используете последнюю версию cfg!.
        /// </summary>
        internal static string AlreadyUsingLatestCFG {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже используете последний хеш-лист!.
        /// </summary>
        internal static string AlreadyUsingLatestHashlist {
            get {
                return ResourceManager.GetString("AlreadyUsingLatestHashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Патчить дамп?.
        /// </summary>
        internal static string autopatch {
            get {
                return ResourceManager.GetString("autopatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите пропатчить этот дамп?.
        /// </summary>
        internal static string autopatchmsg {
            get {
                return ResourceManager.GetString("autopatchmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что-то пошло не так во время загрузки, попробуйте еще раз!.
        /// </summary>
        internal static string baddwl {
            get {
                return ResourceManager.GetString("baddwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА: размер файла не соответствует ожидаемому размеру из конфигурации! Пожалуйста, дважды проверьте свой дамп и конфигурацию!.
        /// </summary>
        internal static string badsize {
            get {
                return ResourceManager.GetString("badsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено получение журнала изменений....
        /// </summary>
        internal static string changelogdone {
            get {
                return ResourceManager.GetString("changelogdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА - Неверный дамп.
        /// </summary>
        internal static string Checks_StartCheck_ERROR___Bad_dump {
            get {
                return ResourceManager.GetString("Checks_StartCheck_ERROR___Bad_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы конфигурации|*.cfg|Все файлы|*.*.
        /// </summary>
        internal static string conf_filter {
            get {
                return ResourceManager.GetString("conf_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на crash.log.
        /// </summary>
        internal static string CrashLogName {
            get {
                return ResourceManager.GetString("CrashLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok... Вы не умеете читать? ну тогда... повезет в следующий раз!.
        /// </summary>
        internal static string DisclaimerFailedMessage {
            get {
                return ResourceManager.GetString("DisclaimerFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание последней версии PS3 Dump Checker.
        /// </summary>
        internal static string dlingapp {
            get {
                return ResourceManager.GetString("dlingapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание последней версии hashlist....
        /// </summary>
        internal static string dlinghashlist {
            get {
                return ResourceManager.GetString("dlinghashlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание последней версии CFG.
        /// </summary>
        internal static string dlinglatestcfg {
            get {
                return ResourceManager.GetString("dlinglatestcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание журнала изменений....
        /// </summary>
        internal static string downloadchangelog {
            get {
                return ResourceManager.GetString("downloadchangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка завершена....
        /// </summary>
        internal static string downloadcompleted {
            get {
                return ResourceManager.GetString("downloadcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА - Неверный размер.
        /// </summary>
        internal static string error_bad_size {
            get {
                return ResourceManager.GetString("error_bad_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА: конфигурация не загружена!.
        /// </summary>
        internal static string error_noconfig {
            get {
                return ResourceManager.GetString("error_noconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА - Нет конфига!.
        /// </summary>
        internal static string error_noconfig_title {
            get {
                return ResourceManager.GetString("error_noconfig_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При загрузке журнала изменений произошла ошибка. Повторите попытку позже....
        /// </summary>
        internal static string ErrorDownloadingChangelog {
            get {
                return ResourceManager.GetString("ErrorDownloadingChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При загрузке обновления произошла ошибка! Повторите попытку позже....
        /// </summary>
        internal static string ErrorDownloadingUpdate {
            get {
                return ResourceManager.GetString("ErrorDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА: вы должны выбрать кастомный файл патча ROS или снять флажок.
        /// </summary>
        internal static string ErrorNoSeletedPatch {
            get {
                return ResourceManager.GetString("ErrorNoSeletedPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При проверке обновлений произошла ошибка! Повторите попытку позже....
        /// </summary>
        internal static string ErrorWhileCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorWhileCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хэш-лист|*.hashlist|Все файлы|*.*.
        /// </summary>
        internal static string hashlist_filter {
            get {
                return ResourceManager.GetString("hashlist_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА HTTP.
        /// </summary>
        internal static string httperror {
            get {
                return ResourceManager.GetString("httperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас уже установлена последняя версия, или онлайн-версия не обновлена должным образом....
        /// </summary>
        internal static string LatestVersionRunningOrNotUpdatedOnline {
            get {
                return ResourceManager.GetString("LatestVersionRunningOrNotUpdatedOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maj {
            get {
                object obj = ResourceManager.GetObject("maj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string N_A {
            get {
                return ResourceManager.GetString("N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет файла.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E3 Flasher|*.bin|Flash Dumper|*.hex|Все файлы|*.*.
        /// </summary>
        internal static string ofdfilter {
            get {
                return ResourceManager.GetString("ofdfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уупс, онлайн-версия плохая! :&apos;(.
        /// </summary>
        internal static string OnlineVersionIsBad {
            get {
                return ResourceManager.GetString("OnlineVersionIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОШИБКА: невозможно исправить {0}, не удается найти: {1}.
        /// </summary>
        internal static string PatchFailedCantFindPatchFile {
            get {
                return ResourceManager.GetString("PatchFailedCantFindPatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, отправьте{0}{1}{0}на Swizzy@xeupd.com!.
        /// </summary>
        internal static string PleaseSendLogTo {
            get {
                return ResourceManager.GetString("PleaseSendLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово!
        ///Приложение перезапустится, чтобы изменения вступили в силу..
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите восстановить все настройки по умолчанию?.
        /// </summary>
        internal static string RestoreDefaultSettings {
            get {
                return ResourceManager.GetString("RestoreDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите Дамп для проверки.
        /// </summary>
        internal static string seldump {
            get {
                return ResourceManager.GetString("seldump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл конфигурации для загрузки.
        /// </summary>
        internal static string select_conf {
            get {
                return ResourceManager.GetString("select_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл патча.
        /// </summary>
        internal static string selpatch {
            get {
                return ResourceManager.GetString("selpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать встроенные патчи.
        /// </summary>
        internal static string UseEmbeddedPatches {
            get {
                return ResourceManager.GetString("UseEmbeddedPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать внутренний патчер.
        /// </summary>
        internal static string UseInternalPatcher {
            get {
                return ResourceManager.GetString("UseInternalPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРЕДУПРЕЖДЕНИЕ!.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !! ПРЕДУПРЕЖДЕНИЕ !!
        ///Дамп не прошёл проверку (A.K.A., вероятно ПЛОХОЙ)! 
        ///Вы действительно хотите патчить этот дамп?.
        /// </summary>
        internal static string warningforcepatch {
            get {
                return ResourceManager.GetString("warningforcepatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы нашли ошибку!.
        /// </summary>
        internal static string YouFoundABug {
            get {
                return ResourceManager.GetString("YouFoundABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы были предупреждены....
        /// </summary>
        internal static string YouveBeenWarned {
            get {
                return ResourceManager.GetString("YouveBeenWarned", resourceCulture);
            }
        }
    }
}
